version: 1.0.{build}

image: Visual Studio 2019

install:
  - npm install

build_script:
  - npm run build

deploy:
  provider: GitHub
  auth_token:
    secure: <GITHUB_TOKEN>
  tag: $(appveyor_build_version)
  on:
    branch: main

