version: 1.0.{build}

image: Visual Studio 2019

install:
  - npm install

build_script:
  - npm run build

deploy:
  provider: GitHub
  auth_token:
    secure: 8pMLdvN8i3pB2fLB7bwKfgsvi6zQ2DZBDu/eK73TWbUVrqkT2zGxmDGdcAq2hASa
  tag: $(appveyor_build_version)
  on:
    branch: main

