version: 1.0.{build}

image: Visual Studio 2019

install:
  - npm install

build_script:
  - npm run build

deploy:
  provider: GitHub
  github_token: $GH_TOKEN
  repository: Mikhail5509/credit-card-validator
  branch: gh-pages
  folder: dist
  on:
    branch: main
